apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-04T06:58:51Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: directus
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: postgresql
  namespace: directus
  resourceVersion: "2170097"
  uid: dec4e543-b46a-4028-af34-16e5e0ef3897
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgresql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgresql
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: postgresql-secrets
        image: postgis/postgis:13-master
        imagePullPolicy: IfNotPresent
        name: postgis
        ports:
        - containerPort: 5432
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          subPath: postgresql-data
          name: postgresql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-pvc
status:
  conditions:
  - lastTransitionTime: "2023-11-04T06:58:52Z"
    lastUpdateTime: "2023-11-04T06:58:52Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-11-04T07:32:40Z"
    lastUpdateTime: "2023-11-04T07:33:13Z"
    message: ReplicaSet "postgresql-7c9d4d8fd5" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
