apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-helm-chart-value-overrides
  namespace: kube-system
data:
  values.yaml: |-
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
        ingressClass: traefik
        
    priorityClassName: "system-cluster-critical"

    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    service:
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv4
    image:
      # -- Traefik image host registry
      registry: docker.io
      # -- Traefik image repository
      repository: traefik
      # -- defaults to appVersion
      tag: "v2.10.5"
      # -- Traefik image pull policy
      pullPolicy: IfNotPresent
