apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 12h0m0s
  url: https://traefik.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      version: 25.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  install:
    crds: Create
  interval: 24h0m0s
  timeout: 10m
  releaseName: traefik
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: traefik-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
