apiVersion: apps/v1
kind: Deployment
metadata:
  name: directus
  namespace: directus
spec:
  selector:
    matchLabels:
      app: directus
  template:
    metadata:
      labels:
        app: directus
    spec:
      containers:
      - name: directus
        image: ghcr.io/directus/directus:10.7.2
        # load a secret for env vars:
        envFrom:
        - secretRef:
            name: directus-env
        ports:
        - containerPort: 8055
        volumeMounts:
        - name: directus-uploads
          mountPath: /directus/uploads
        - name: directus-extensions
          mountPath: /directus/extensions
        securityContext:
          allowPrivilegeEscalation: false

        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: directus-uploads
        persistentVolumeClaim:
          claimName: directus-uploads
      - name: directus-extensions
        persistentVolumeClaim:
          claimName: directus-extensions
