apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: directus
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
        image: postgres:13
        envFrom:
        - secretRef:
            name: postgresql-secrets
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"

        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-pvc
