apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: directus
  labels:
    app: postgresql
spec:
  storageClassName: longhorn-rwx
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-pvc
#   namespace: directus
#   labels:
#     app: redis
# spec:
#   storageClassName: longhorn
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 512Mi
