# FILEPATH: /Users/ngeorger/sredevops/webprojects/apps/directus/postgres-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-rwx
  csi:
    driver: driver.longhorn.io
    volumeHandle: postgresql-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-rwx
  selector:
    matchLabels:
      app: postgresql
