# Redis configmap for initial configuration and to enable persistence
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: directus
data:
  redis.conf: |
    port 6379
    dir /data
    appendonly yes
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    maxmemory-samples 10
    requirepass ${REDIS_PASSWORD}
    masterauth ${REDIS_PASSWORD}
    save 900 1
    save 300 10
    save 60 10000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: directus
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        envFrom:
        - secretRef:
            name: redis-secrets
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
          #  mount configmap as the redis config file in /usr/local/etc/redis/redis.conf
        - name: config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
      volumes:
      - name: redis-data
        emptyDir:
          medium: Memory
          sizeLimit: 128Mi


      - name: config
        valueFrom:
          configMapKeyRef:
            name: redis-config
            key: redis.conf

