apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: directus
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        command: ["redis-server", "--bind 0.0.0.0", "--port 6379", "--requirepass $REDIS_PASSWORD", "--user $REDIS_USER on", "--appendonly yes", "--save 60 1"]
        securityContext:
          #   capabilities:
          #     drop:
          #     - ALL
          #     add:
          #     - NET_BIND_SERVICE
          #     - CHOWN
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        envFrom:
        - secretRef:
            name: redis-secrets
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
          readOnly: false

      volumes:
      - name: redis-data
        emptyDir:
          medium: Memory
          sizeLimit: "256Mi"
