apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: directus
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        command: ["redis-server", "/etc/redis/redis.conf"]
        securityContext:
          #   capabilities:
          #     drop:
          #     - ALL
          #     add:
          #     - NET_BIND_SERVICE
          #     - CHOWN
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        envFrom:
        - secretRef:
            name: redis-secrets
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
          readOnly: false
        - name: config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
          readOnly: true
      volumes:
      - name: redis-data
        emptyDir:
          medium: Memory
          sizeLimit: "256Mi"
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis.conf
            path: redis.conf
