apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: directus
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        command: ["redis-server", "/etc/redis/redis.conf"]
        # command: ["redis-server", "--bind 0.0.0.0", "--port 6379", "--requirepass $REDIS_PASSWORD", "--user $REDIS_USER on", "--appendonly yes", "--save 60 1", "--maxmemory 256mb", "--maxmemory-policy allkeys-lru", "--database 0", "--dir /data"]
        securityContext:
          #   capabilities:
          #     drop:
          #     - ALL
          #     add:
          #     - NET_BIND_SERVICE
          #     - CHOWN
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          limits:
            memory: 256Mi
            cpu: 250m
          requests:
            memory: 0Mi
            cpu: 0m
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
          readOnly: false
        - name: redis-config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
          readOnly: true
      volumes:
      - name: redis-data
        emptyDir:
          medium: Memory
          sizeLimit: 256Mi          
      - name: redis-config
        secret:
          secretName: redis-secrets
