apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: directus
data:
  redis.conf: |
    port 6379
    dir /data
    appendonly yes
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    maxmemory-samples 10
    requirepass ${REDIS_PASSWORD}
    masterauth ${REDIS_PASSWORD}
    save 900 1
    save 300 10
    save 60 10000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: directus
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
          # runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        envFrom:
        - secretRef:
            name: redis-secrets
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
          readOnly: false
          # subPath: redis-data
        - name: config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
          readOnly: true
      volumes:
      - name: redis-data
        emptyDir:
          medium: Memory
          sizeLimit: 128Mi
      - name: config # use configmap as volume
        configMap:
          name: redis-config
          items:
          - key: redis.conf
            path: redis.conf
