apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1h0m0s
  ref:
    branch: staging
  url: https://github.com/sredevopsdev/webprojects.git
  secretRef:
    name: github-sredevops-creds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: directus
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: flux-system
